# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Run project
      run: |
        SSH_USER=ec2-user
        SSH_HOST=ec2-13-50-99-27.eu-north-1.compute.amazonaws.com
        SSH_PRIVATE_KEY=MIIEogIBAAKCAQEAhjPu9UcqSsh+jOdcgUvw1spWd0SVovB7Sz8McO6QoS26bGmoj1YyvDbKHg6HDCUWaWh1Y5W/YzoKDwoyvgLhUJ/Lt2zZpFB8HgPZ2Rg5rTUF3IWfccbGX1OS43jMwOCZAoWSFvTUTXN0poFP/8AiScz7wy4eMs+ctaPIvHBcNbRxAIt+8L/chkaCrgz/70D/T7wiegaR97VZ+pfynY4FqyJ6iILDhXailoe5T+AtlX/M9tEwAPxdbO22XqyztwWJsCj44g9T5PgiACwynfBUXkt53yXkcRnfw55mEvuF+PJu9EJqDOWpgD7Il5yPOWkeWOIQiGoIQvCgYtrKPivdrwIDAQABAoIBAD2LfY/ApjWLgvXNeI/XKsjmHAcwTcteq7xTWrpDvdIc7Xyga+voJPZJziFAmlBIheGrRQJ5fz7bNBe3npOjMH9P+RXSdnEzc+gz7ejwgirbwSdjpD6CYSEAa8Gj+YqOtb0BUoDyoJYwV5Owg+aOz2q29dKJyNGWgpCOXxWEFdWOkgevpDyZhrCB3zTSh6MiOKZGMsGUIws7jF1N9XncbISE/O/2j5aQvgRmwZ7PexirrzlmJNTSgVHEgOCdcJI2UNnQQDlOTkOJawwhKJBTEMxVqTJU8SxrRAN7NAZn7q0tVM27Gfym9qGPLtdi41AjyCgC4PwjbgO8mn3QmPFr/TkCgYEA1QudCRmo0J7DCbMBV4xq4M4EC5Ssn2MiKRa4VMlUf2RyWLHqJcxE8kxcs7uX5zix3KOovw691UUFEl8qYdhWYfSqVKYtQG+sttq9BanAjC+GahdQ1TtwffyXuTjtGVi7/HzTddXUn0yCabQ2Zq5S76Tv9mJbj203PYkCAR/kw2MCgYEAoULYiU9EvdkC+gswWSGvgpx5e+RzC0L2L/RV4wumfQscXOi3tag5V1Io26z9ycf1jjm/GcJa05YjVtf1Zq597kd/4oK++miuvRlauigN3zPij/9zp66kwM2iTFC3j1fWayY3wMdZPfxAxELku/WOq+pFe2u8h796qON6xxLoPEUCgYBTiO81H0OLMYUmK3MuQdeyd/UsGUqqYHOHiuoSDLM+FEOltXUrBvJN01VSAA9q0VckPWOwLnaOxjZb4sa6gNo2JHoZIOODbYZaWGBfdRUToprgxG2kfl74d2+CZ+jH1Hw5XzSG8qYhJB3KlqfyEQ5h+tlAUYa3MUrErREFId1QIwKBgGE/kJntpcTfc/4adUOrHs6jUle2gvJNpW1x6cGMKxDJfIdDCFaSZlIUh/NCNaJT5e+pP2dnX6Ktrg4XGjScEfF6SNLuigE00/vRqHcO5J6wCXdRVAvRNCXZXICtRKU7EWF4oLKvBVBuKRiyRoJbKXjfRJuTcxRiErR6ynX3HvoJAoGAZMsSdCerA65vBM6m746yY/Ra2fXsCfjl68tkmsPZfAoYOwzmXJHBpI4dGJMV/44FtK02okMiqjNlsXMpfkB6z6d0e31FpQEz9eCSdXLf3f5WrGw2m6zsffdEOC++lZ/XMR+ZqDtjTuW6EYqNjbChOPsxgFDdqWuiFf0RmQ48jfk=
        ssh -i "$SSH_PRIVATE_KEY" "$SSH_USER"@"$SSH_HOST" "cd /home/ec2-user/actions-runner/_work/back-end-Spring/back-end-Spring && java -jar target/Back-End-0.0.1.jar"
      
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
